[consul_servers]
consul-srv-1 ansible_host= consul_node_role=server
consul-srv-2 ansible_host= consul_node_role=server
consul-srv-3 ansible_host= consul_node_role=server

[load_balancers]
lb-01 ansible_host= consul_node_role=client

[monitoring]
monitoring-1 ansible_host=consul_node_role=client

[backends]
backend-v1 ansible_host= consul_node_role=client

[consul_clients:children]
backends
load_balancers
monitoring

[elastic_nodes]
consul-srv-1 ansible_host= consul_node_role=server
consul-srv-2 ansible_host= consul_node_role=server
consul-srv-3 ansible_host= consul_node_role=server

[kibana]
monitoring-1 ansible_host= consul_node_role=client

[log_clients:children]
load_balancers
monitoring
backends


[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
